package org.firstinspires.ftc.teamcode;

public enum M {
    DRIVE, STRAFE, ROTATE, WOBBLE_UP, WOBBLE_DOWN, WOBBLE_OPEN, WOBBLE_CLOSE, MAG_PUSH, WAIT, SHOOTER_ON, SHOOTER_OFF, INTAKE_FORWARD, INTAKE_BACKWARD, INTAKE_OFF, STRAFE_TILL, DRIVETURN, CORRECT
}