package org.firstinspires.ftc.teamcode;

public enum M {
    DRIVE, STRAFE, ROTATE, BACK_DOWN, BACK_UP, SKYSTONE_DOWN, SKYSTONE_UP, SKYSTONE_POS, BACK_UP_SKYSTONE_HALF, STRAFE_TILL, SKYSTONE_DOWN_GRIPPER_OUT, GRIPPER_IN, BACK_HALF, DRIVETURN, CORRECT
};